openapi: 3.2.0
info:
  title: Data Plane Inference API
  version: '2.0'
  contact:
    name: Seldon Technologies Ltd.
    url: https://www.seldon.io/
    email: hello@seldon.io
  description: REST protocol to interact with inference servers.
  license:
    name: Business Source License 1.1
servers: []
tags:
- name: inference
paths:
  /v2/models/{model_name}/versions/{model_version}/infer:
    parameters:
    - schema:
        type: string
      name: model_name
      in: path
      required: true
    - schema:
        type: string
      name: model_version
      in: path
      required: true
    post:
      summary: Model Inference
      operationId: model-version-inference
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferenceRequest'
      description: An inference request is made with an HTTP POST to an inference endpoint. The model name and (optionally) version must be available in the URL. If a version is not provided the server may choose a version based on its own policies or return an error.
      tags:
      - inference
  /v2/models/{model_name}/infer:
    parameters:
    - schema:
        type: string
      name: model_name
      in: path
      required: true
    post:
      summary: Model Inference
      operationId: model-inference
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferenceRequest'
      description: An inference request is made with an HTTP POST to an inference endpoint. The model name and (optionally) version must be available in the URL. If a version is not provided the server may choose a version based on its own policies or return an error.
      tags:
      - inference
components:
  schemas:
    ResponseOutput:
      title: ResponseOutput
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        data:
          $ref: '#/components/schemas/TensorData'
      required:
      - name
      - shape
      - datatype
      - data
    RequestOutput:
      title: RequestOutput
      type: object
      properties:
        name:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
      required:
      - name
    Parameters:
      type: object
      title: Parameters
      x-examples: {}
      additionalProperties: true
      properties:
        content_type:
          type: string
        headers:
          type: object
    InferenceErrorResponse:
      title: InferenceErrorResponse
      type: object
      properties:
        error:
          type: string
    InferenceRequest:
      title: InferenceRequest
      type: object
      x-examples:
        Example 1:
          id: '42'
          inputs:
          - name: input0
            shape:
            - 2
            - 2
            datatype: UINT32
            data:
            - 1
            - 2
            - 3
            - 4
          - name: input1
            shape:
            - 3
            datatype: BOOL
            data:
            - true
          outputs:
          - name: output0
        Example 2:
          id: '42'
          outputs:
          - name: output0
            shape:
            - 3
            - 2
            datatype: FP32
            data:
            - 1
            - 1.1
            - 2
            - 2.1
            - 3
            - 3.1
      properties:
        id:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/RequestInput'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/RequestOutput'
      required:
      - inputs
    InferenceResponse:
      title: InferenceResponse
      type: object
      properties:
        model_name:
          type: string
        model_version:
          type: string
        id:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/ResponseOutput'
      required:
      - model_name
      - outputs
    RequestInput:
      title: RequestInput
      type: object
      properties:
        name:
          type: string
        shape:
          type: array
          items:
            type: integer
        datatype:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
        data:
          $ref: '#/components/schemas/TensorData'
      required:
      - name
      - shape
      - datatype
      - data
    TensorData:
      title: TensorData
